\"
\" lz4.1: This is a manual page for 'lz4' program. This file is part of the
\" lz4 <https://code.google.com/p/lz4/> project.
\"

\" No hyphenation
.hy 0
.nr HY 0

.TH lz4 "1" "2014-02-27" "lz4" "User Commands"
.SH NAME
\fBlz4\fR - Extremely fast compression algorithm

.SH SYNOPSIS
.TP 5
\fBlz4\fR [\fBOPTIONS\fR] [-|INPUT-FILE] <OUTPUT-FILE>

.SH DESCRIPTION
.PP
\fBlz4\fR is an extremely fast lossless compression algorithm. It is based on
the \fBLZ77\fR family of compression scheme. At the compression speed of 400
MB/s per core, \fBlz4\fR is also scalable with multi-core CPUs. It features
an extremely fast decoder, with speed in multiple GB/s per core, typically
reaching the RAM speed limits on multi-core systems. \fBlz4\fR supports
following options

.SH OPTIONS
.TP
.B \-1
 fast compression (default)
.TP
.B \-9
 high compression
.TP
.B \-d
 decompression
.TP
.B \-f
 overwrite output without prompting
.TP
.B \-h/\-H
 display help/long help and exit
.TP
.B \-V
 display Version number and exit
.TP
.B \-v
 verbose mode
.TP
.B \-q
 suppress warnings; specify twice to suppress errors too
.TP
.B \-c
 force write to standard output, even if it is the console
.TP
.B \-t
 test compressed file integrity
.TP
.B \-z
 force compression
.TP
.B \-l
 use Legacy format (useful for Linux Kernel compression)
.TP
.B \-B#
 block size [4-7](default : 7)
 B4= 64KB ; B5= 256KB ; B6= 1MB ; B7= 4MB
.TP
.B \-BD
 block dependency (improve compression ratio)
.TP
.B \-BX
 enable block checksum (default:disabled)
.TP
.B \-Sx
 disable stream checksum (default:enabled)
.TP
.B \-b
 benchmark file(s)
.TP
.B \-i#
 iteration loops [1-9](default : 3), benchmark mode only

.SH BUGS
Report bugs at:- https://code.google.com/p/lz4/

.SH AUTHOR
Yann Collet
